INSERT INTO medicos (name, email, especialidad) VALUES
('Dr. Carlos Mendoza',      'carlos.mendoza@medmanage.com',    'Cardiología'),
('Dra. Sofía Ramírez',      'sofia.ramirez@medmanage.com',     'Pediatría'),
('Dr. Andrés Castellanos',  'andres.castellanos@medmanage.com','Neurología'),
('Dra. Valeria Torres',     'valeria.torres@medmanage.com',    'Ginecología'),
('Dr. Luis Herrera',        'luis.herrera@medmanage.com',      'Ortopedia'),
('Dra. Gabriela Fuentes',   'gabriela.fuentes@medmanage.com',  'Dermatología'),
('Dr. Miguel Ángel Rojas',  'miguel.rojas@medmanage.com',      'Traumatología'),
('Dra. Patricia Vásquez',   'patricia.vasquez@medmanage.com',  'Oncología'),
('Dr. Roberto Aguilar',     'roberto.aguilar@medmanage.com',   'Urología'),
('Dra. Ana Lucía Morales',  'ana.morales@medmanage.com',       'Endocrinología'),
('Dr. Javier Espinoza',     'javier.espinoza@medmanage.com',   'Oftalmología'),
('Dra. Carmen Delgado',     'carmen.delgado@medmanage.com',    'Reumatología'),
('Dr. Fernando Ríos',       'fernando.rios@medmanage.com',     'Gastroenterología'),
('Dra. Isabel Sánchez',     'isabel.sanchez@medmanage.com',    'Neumología'),
('Dr. Ricardo Peña',        'ricardo.pena@medmanage.com',      'Psiquiatría'),
('Dra. Mónica Jiménez',     'monica.jimenez@medmanage.com',    'Medicina Interna'),
('Dr. Héctor Vargas',       'hector.vargas@medmanage.com',     'Cirugía General'),
('Dra. Alejandra Núñez',    'alejandra.nunez@medmanage.com',   'Nefrología'),
('Dr. Pablo Gutiérrez',     'pablo.gutierrez@medmanage.com',   'Infectología'),
('Dra. Lorena Campos',      'lorena.campos@medmanage.com',     'Hematología');
